apiVersion: v1
kind: Secret
metadata:
  name: <SECRET_NAME>
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://<CODE_COMMIT_URL>
  # https://git-codecommit.ap-northeast-2.amazonaws.com/v1/repos/retail-store-sample-app-assets-kustomize
  username: <CODE_COMMIT_ACCESS_KEY>
  password: <CODE_COMMIT_SECRET_KEY>
